version: '3'
services:
    api:
        build:
            context: .
        volumes:
            # Files for Digital Editions need to be mounted
            # Syntax is host_path:container_path
            # This example mounts the host's /var/files/topelius to /var/topelius-files in the container and so on
            #- /var/files/topelius:/var/topelius-files/
            #- /var/files/parland:/var/parland-files/
            #- /var/files/xslt:/var/xslt-files/
            - D:\Development\generic\granqvist_files\required_files:/var/topelius

            # Config files need to be mounted aswell
            - ./sls_api/configs:/app/sls_api/configs
        restart: always
        ports:
            # Port syntax is host_port:container_port
            # Dockerfile uses port 8000
            - "8000:8000"
