# For more information on database engine configurations, see http://docs.sqlalchemy.org/en/latest/core/engines.html

engine: 'mysql://web_user:SecretPassword@mysql_server.example.com:3306'
# This engine config tells the system to connect to a MySQL server at mysql_server.example.com on port 3306
# It uses the username 'web_user' with the password 'SecretPassword'

parland:
    git_repository: 'publisher@parland:slsfi/parland.git'
    git_config: |
        host parland
          HostName github.com
          IdentityFile ~/.ssh/github-id-rsa
          User publisher
    git_branch: 'staging'
    file_root: '/var/www/parland'

topelius:
    git_repository: 'publisher@topelius:slsfi/topelius.git'
    git_config: |
        host topelius
          HostName bitbucket.org
          IdentityFile ~/.ssh/bitbucket-id-rsa
          User publisher
    git_branch: 'master'
    file_root: '/var/www/topelius'

log_file: '/log/digital_editions/api.log'
cache_lifetime_seconds: 7200  # 2 hours
