parland:
    address: "mysql_server.example.com"
    username: "web_user"
    password: "SecretMySQLPassword"
    database: "parland"
    show_internally_published: True
    show_unpublished: True
    disabled_publications: []
    file_root: "/var/parland-files"
topelius:
    address: "mysql_server.example.com"
    username: "web_user"
    password: "SecretMySQLPassword"
    database: "topelius"
    show_internally_published: True
    show_unpublished: True
    disabled_publications: [10,12,13,14,9,20,28]
    file_root: "/var/topelius-files"
semantic_data:
    address: "mysql_server.example.com"
    username: "web_user"
    password: "SecretMySQLPassword"
    database: "semantic_data"
xslt_root: "/var/xslt-files"
log_file: "/log/digital_editions/api.log"
