# For more information on database engine configurations, see http://docs.sqlalchemy.org/en/latest/core/engines.html

# Database configuration
# This engine config connects to a MySQL server at mysql_server_example.com, on port 3306
# It connects as the user 'web_user', using the password 'SecretPassword'
# It connects to a database named 'Metadata'
engine: 'mysql://web_user:SecretPassword@mysql_server.example.com:3306/Metadata'

# Identify verb data
repo_name: 'Company/RepoName'
repo_protocol_ver: '2.0'
repo_admin: 'admin@company.com'
repo_deletion: 'persistent'
repo_granularity: 'YYYY-MM-DD'

# ListSets verb data
sets:
    # Sets are defined as setSpec: 'setName'
    CompanySet1: 'Full Set Name'
    otherSet: 'Long Set Name'
