# For more information on database engine configurations, see http://docs.sqlalchemy.org/en/latest/core/engines.html

# Database configuration
# This engine config connects to a sqlite3 database named library.db
engine: 'sqlite:///library.db'

# Database information
id_column: "ID"
date_column: "Datum"
table: "library"

# Record metadata mappings
namespace_map:
    # Maps namespaces to their URLs
    xml: "http://www.w3.org/XML/1998/namespace"
    dc: "http://purl.org/dc/elements/1.1/"
    dcterms: "http://purl.org/dc/terms/"

record_map:
    # Maps database columns to OAI elements, should use namespaces from namespace_map
    ID: "dc:identifier"
    Creator: "dc:creator"
    Title: "dc:title"
    Date: "dc:date"
    Publisher: "dc:publisher"
    Publishing_city: "dcterms:provenance"
    Pages: "dcterms:extent"
    Language: "dc:language"
    Series: "dcterms:isPartOf"
    Series_part: "dcterms:isPartOf"
    Subjects: "dc:subject"
    Description: "dc:description"
    placement: "dcterms:spatial"
    shelf_place: "dcterms:spatial"
    type: "dc:type"

# Identify verb data
repo_name: 'Company/RepoName'
repo_protocol_ver: '2.0'
repo_admin: 'admin@company.com'
repo_deletion: 'no'
repo_granularity: 'YYYY-MM-DD'

# ListSets verb data
sets:
    # Sets are defined as setSpec: 'setName'
    CompanySet1: 'Full Set Name'
    otherSet: 'Long Set Name'
